# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

default: &default
  locastyle:
    css:   "http://assets.locaweb.com.br/locastyle/3.8.1/stylesheets/locastyle.css"
    js:    "http://assets.locaweb.com.br/locastyle/3.8.1/javascripts/locastyle.js"

  site:
    name: Commit-Crap
    title: Commit-Crap
    domain: commitcrap.com.br
    url: http://www.commitcrap.com.br
    email: commitcrap@commitcrap.com.br

development: &development
  <<: *default
  secret_key_base: 27084885727c14b5718586a40fe5649bb905babc4f63c075fa85a2bf29f48ffb177ea1425c95277806d240d6f3fcb3c35eaef0761ab6c42846f2092553fbab45

test:
  <<: *default
  secret_key_base: 056281b870f50cc4c2adaaf0347ed828b0d4400d13769f6639eb7a8aca866a1ff1c720763e29ccbc8468034164a60da0027826507c6e682fa459c474e7d6f1a7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  <<: *default
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
